# Generated by Django 6.0.5 on 2026-05-07 13:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='概念名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概念描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '概念板块',
                'verbose_name_plural': '概念板块',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockDailyKline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('open', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='开盘价')),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最高价')),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最低价')),
                ('close', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额')),
                ('amplitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='振幅')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='换手率')),
                ('change_amt', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='涨跌额')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='涨跌幅')),
            ],
            options={
                'verbose_name': '日K线数据',
                'verbose_name_plural': '日K线数据',
                'ordering': ['-trade_date'],
            },
        ),
        migrations.CreateModel(
            name='StockFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='报告期')),
                ('report_type', models.CharField(blank=True, choices=[('年报', '年报'), ('半年报', '半年报'), ('季报', '季报')], max_length=20, null=True, verbose_name='报告类型')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='营业收入')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='净利润')),
                ('eps', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='每股收益')),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='净资产收益率')),
                ('pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率')),
                ('pb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市净率')),
            ],
            options={
                'verbose_name': '财务数据',
                'verbose_name_plural': '财务数据',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='板块')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('total_shares', models.BigIntegerField(blank=True, null=True, verbose_name='总股本')),
                ('float_shares', models.BigIntegerField(blank=True, null=True, verbose_name='流通股本')),
                ('status', models.CharField(choices=[('LISTING', '上市'), ('DELISTING', '退市'), ('ST', '特别处理'), ('PAUSED', '停牌')], default='LISTING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMinuteKline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('period', models.CharField(choices=[('1min', '1分钟'), ('5min', '5分钟'), ('15min', '15分钟'), ('30min', '30分钟'), ('60min', '60分钟')], default='1min', max_length=10, verbose_name='K线周期')),
                ('open', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='开盘价')),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最高价')),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最低价')),
                ('close', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额')),
            ],
            options={
                'verbose_name': '分钟K线数据',
                'verbose_name_plural': '分钟K线数据',
                'ordering': ['-trade_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='评分')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='入选原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '选股结果明细',
                'verbose_name_plural': '选股结果明细',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='持仓股数')),
                ('available_shares', models.BigIntegerField(default=0, verbose_name='可用股数')),
                ('cost_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='成本价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户持仓',
                'verbose_name_plural': '用户持仓',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('USER', '普通用户'), ('ADMIN', '管理员'), ('ANALYST', '分析师')], default='USER', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('INACTIVE', '未激活'), ('BANNED', '封禁')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作类型')),
                ('target', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作对象')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
                ('ip_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务名称')),
                ('strategy', models.CharField(blank=True, max_length=50, null=True, verbose_name='选股策略')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='策略参数')),
                ('status', models.CharField(choices=[('PENDING', '等待'), ('RUNNING', '执行中'), ('COMPLETED', '完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '选股任务',
                'verbose_name_plural': '选股任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_task_status'), models.Index(fields=['-created_at'], name='idx_task_created_at')],
            },
        ),
        migrations.CreateModel(
            name='StockConceptRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockconcept', verbose_name='概念')),
            ],
            options={
                'verbose_name': '股票概念关联',
                'verbose_name_plural': '股票概念关联',
            },
        ),
        migrations.CreateModel(
            name='StockRealtime',
            fields=[
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.stockinfo', verbose_name='股票代码')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最新价')),
                ('open', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='今日开盘价')),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='今日最高价')),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='今日最低价')),
                ('prev_close', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='昨收价')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额')),
                ('bid1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='买一价')),
                ('bid_vol1', models.BigIntegerField(blank=True, null=True, verbose_name='买一量')),
                ('bid2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='买二价')),
                ('bid_vol2', models.BigIntegerField(blank=True, null=True, verbose_name='买二量')),
                ('bid3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='买三价')),
                ('bid_vol3', models.BigIntegerField(blank=True, null=True, verbose_name='买三量')),
                ('bid4', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='买四价')),
                ('bid_vol4', models.BigIntegerField(blank=True, null=True, verbose_name='买四量')),
                ('bid5', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='买五价')),
                ('bid_vol5', models.BigIntegerField(blank=True, null=True, verbose_name='买五量')),
                ('ask1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='卖一价')),
                ('ask_vol1', models.BigIntegerField(blank=True, null=True, verbose_name='卖一量')),
                ('ask2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='卖二价')),
                ('ask_vol2', models.BigIntegerField(blank=True, null=True, verbose_name='卖二量')),
                ('ask3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='卖三价')),
                ('ask_vol3', models.BigIntegerField(blank=True, null=True, verbose_name='卖三量')),
                ('ask4', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='卖四价')),
                ('ask_vol4', models.BigIntegerField(blank=True, null=True, verbose_name='卖四量')),
                ('ask5', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='卖五价')),
                ('ask_vol5', models.BigIntegerField(blank=True, null=True, verbose_name='卖五量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '实时行情',
                'verbose_name_plural': '实时行情',
            },
        ),
        migrations.AddIndex(
            model_name='stockinfo',
            index=models.Index(fields=['name'], name='idx_stock_info_name'),
        ),
        migrations.AddField(
            model_name='stockfinancial',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stockinfo', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='stockdailykline',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_klines', to='stocks.stockinfo', verbose_name='股票代码'),
        ),
        migrations.AddField(
            model_name='stockconceptrel',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockinfo', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='stockminutekline',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_klines', to='stocks.stockinfo', verbose_name='股票代码'),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stockinfo', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stocks.selectiontask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='stocks.stockinfo', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_log_user_time'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['action'], name='idx_log_action'),
        ),
        migrations.AddIndex(
            model_name='stockfinancial',
            index=models.Index(fields=['stock', '-report_date'], name='idx_financial_code_date'),
        ),
        migrations.AlterUniqueTogether(
            name='stockfinancial',
            unique_together={('stock', 'report_date', 'report_type')},
        ),
        migrations.AddIndex(
            model_name='stockdailykline',
            index=models.Index(fields=['trade_date'], name='idx_daily_kline_date'),
        ),
        migrations.AddIndex(
            model_name='stockdailykline',
            index=models.Index(fields=['code', '-trade_date'], name='idx_daily_kline_code_date'),
        ),
        migrations.AlterUniqueTogether(
            name='stockdailykline',
            unique_together={('code', 'trade_date')},
        ),
        migrations.AlterUniqueTogether(
            name='stockconceptrel',
            unique_together={('stock', 'concept')},
        ),
        migrations.AddIndex(
            model_name='stockminutekline',
            index=models.Index(fields=['code', '-trade_time'], name='idx_minute_kline_code_time'),
        ),
        migrations.AddIndex(
            model_name='stockminutekline',
            index=models.Index(fields=['period'], name='idx_minute_kline_period'),
        ),
        migrations.AlterUniqueTogether(
            name='stockminutekline',
            unique_together={('code', 'trade_time', 'period')},
        ),
        migrations.AddIndex(
            model_name='taskdetail',
            index=models.Index(fields=['stock'], name='idx_detail_stock'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user'], name='idx_portfolio_user'),
        ),
        migrations.AlterUniqueTogether(
            name='userportfolio',
            unique_together={('user', 'stock')},
        ),
    ]
