# Generated by Django 6.0.5 on 2026-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=50, unique=True, verbose_name='配置键名')),
                ('config_value', models.JSONField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['config_key'],
            },
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='action',
            field=models.CharField(blank=True, choices=[('LOGIN', '登录'), ('LOGOUT', '登出'), ('SELECT_STOCK', '选股'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('DELETE', '删除'), ('UPDATE', '更新'), ('CREATE', '创建'), ('VIEW', '查看'), ('DOWNLOAD', '下载')], max_length=50, null=True, verbose_name='操作类型'),
        ),
    ]
